### ISSUE TITLE
Create conda package

### ISSUE THREAD

**Issue by frreiss** [CODAIT/text-extensions-for-pandas#145]
This issue covers adding an Anaconda package to the next release of this library.

Instructions for converting pip packages to conda packages can be found [here](https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html).

We'll need to update the release checklist to cover building the anaconda packages too. Anaconda appears to require separate packages for every combination of OS and Python version, even if the underlying Python package is OS and Python version-independent.

**Comment by BryanCutler** [comment]
I'm working on this. The linked instructions above didn't quite work, so I am building the recipe from scratch. It's currently done but test build of the package fails due to unit tests with Pandas 1.2.0, to be fixed in #157 . Once we get that resolved, we will need to do another beta release to PyPi. With that, I can put up a PR to the conda forge staged recipe repo. After that is accepted, packages will automatically be built and available in conda forge. Does that sound ok with you @frreiss ?

**Comment by frreiss** [comment]
Sounds great, thanks @BryanCutler !

**Comment by BryanCutler** [comment]
PR for setting up conda-forge package https://github.com/conda-forge/staged-recipes/pull/13885

**Comment by BryanCutler** [comment]
The recipe has been merged and the package should appear in conda-forge at some point. I'll test it out and add to our installation instructions once it's there.

**Comment by BryanCutler** [comment]
https://github.com/conda-forge/text_extensions_for_pandas-feedstock
